#!/usr/bin/sh
#use tesseract to copy any text on screen to clipboard
#can take languages from the command line in format 'lang1+lang2+lang3'
#if no languages are supplied, defaults to english
LANGS=$1
test -z "$LANGS" && LANGS="eng"
TEXT=$(maim -s | tesseract -l $LANGS - -)
test -z "$TEXT" && {
    notify-send "tessgrab: Failed to recognize any text"
    exit 1
} || echo $TEXT | xsel -ib && notify-send "tessgrab: Copied '$TEXT' to clipboard"
